### ISSUE TITLE
GRG configuration page Lock Settings toggle switch

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-grg-widget#157]
### Bug or Enhancement
The Lock Settings toggle positions for "on" and "off" are reversed in the configuration.

### Repo Steps or Enhancement details
1. Add GRG widget to an app
2. Click the configure this widget button to open the widget configuration
3. Note the Lock Settings toggle switch

**Comment by adgiles** [comment]
Addressed in PR https://github.com/Esri/solutions-grg-widget/pull/158

**Comment by dfoll** [comment]
I got this into devtopia and requested another code review on all the stuff from the past week. https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/pull/11651 if anyone wants to give it a look and make sure it's all good

@adgiles @kgonzago

**Comment by kgonzago** [comment]
@dfoll Looks like string issues still need to be addressed based on Junshan's [last response](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/pull/11651#issuecomment-1038019) to your commit.
