### ISSUE TITLE
Add alpha-alpha, alphanumeric, and numeric labels (with label origin options) to GRGs created from MGRS grids

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/solutions-grg-widget#49]
After the September release, we should add the labeling functionality that we currently have for non-MGRS GRG labels to the GRGs created from MGRS (both point and area)

Label types
- [x] alpha-alpha
- [x] alphanumeric
- [x] numeric

Label start position
- [x] lower-left
- [x] upper-left
- [x] lower-right
- [x] upper-right

This will have to handle the zipper/grid zone issues discussed here: https://github.com/ArcGIS/solutions-grg-widget/issues/44

**Comment by topowright** [comment]
@adgiles has been able to  make headway on the feature based on polygons.

**Comment by adgiles** [comment]
Addressed in PR #125

**Comment by dfoll** [comment]
- [ ] verified fix is good in WAB 2.6 DE
- [ ] updated checklist test (i didn't actually do this, it was already in there, just acknowledging that this step was addressed (Removed G-QA Create (Checklist))
- [ ] updated workflow documentation
- [ ] added a note to the release item to include this functionality in the "what's new"/"release notes

**Comment by dfoll** [comment]
@adgiles Questions:
Was MGRS and USNG implemented, I expected only MGRS but I see both are there (bonus)
Label direction still not available when defining a grid by reference system? (wasn't part of this issue, just making sure)

**Comment by adgiles** [comment]
@dfoll I didn't see label direction as part of this issue, I just implemented what was described by Dan above.

**Comment by dfoll** [comment]
@adgiles perfect....i was just making sure i wasn't missing anything on my end.

**Comment by topowright** [comment]
I have verified that the checklist allows a tester to understand what they are supposed to be testing if they have intimate knowledge of the widget.

**Comment by topowright** [comment]
I need to understand the workflow better between CMS and our website. I am not sure where these doc updates are. I have spent time reviewing **create-grg-from-area-using-widget**, but I am not sure where the doc updates are located in this topic.

**Comment by topowright** [comment]
Also, @lfunkhouser these topics are written differently than the rest of our solutions. I like the idea of grouping larger topics into one general topic. Just FYI

**Comment by dfoll** [comment]
updated documentation is in cms until it gets published as part of the release process
